export const GET_USERS = "GET_USERS"
export const GET_GRUPO = "GET_GRUPO"
export const GET_ARTISTAS = "GET_ARTISTAS"
export const GET_PERFORMANCES = "GET_PERFORMANCES"
export const UPDATE_PERFORMANCE = "UPDATE_PERFORMANCE"
export const ADD_PERFORMANCES = "ADD_PERFORMANCE"
export const DELETE_PERFORMANCE = "DELETE_PERFORMANCE"

