DROP DATABASE IF EXISTS comando_db;

CREATE DATABASE comando_db;

USE comando_db;


CREATE TABLE User (
 id INTEGER AUTO_INCREMENT, 
 name VARCHAR(200) NOT NULL,
 email VARCHAR(200) NOT NULL,
 password VARCHAR(200) NOT NULL,
 PRIMARY KEY(id)
);

CREATE TABLE Performance (
id INTEGER AUTO_INCREMENT,
name VARCHAR(300) NOT NULL,
data VARCHAR(300) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE Grupo (
    id INTEGER AUTO_INCREMENT,
    name VARACHAR(300) NOT NULL,
    invite_code VARCHAR(300) NOT NULL,
    PRIMARY KEY(id)
);
