DROP DATABASE IF EXISTS comando_db;

CREATE DATABASE comando_db;

USE comando_db;


CREATE TABLE users (
 id INTEGER AUTO_INCREMENT, 
 name VARCHAR(200) NOT NULL,
 email VARCHAR(200) NOT NULL,
 password VARCHAR(200) NOT NULL,
 PRIMARY KEY(id)
);

CREATE TABLE performance (
id INTEGER AUTO_INCREMENT,
name VARCHAR(200) NOT NULL,
location VARCHAR(100) NOT NULL,
date VARCHAR(300) NOT NULL,
active BOOLEAN default true,
PRIMARY KEY(id)
);

CREATE TABLE grupo ()